//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::apex_tier_players::Entity as ApexTierPlayers;
pub use super::demotions::Entity as Demotions;
pub use super::dodges::Entity as Dodges;
pub use super::player_counts::Entity as PlayerCounts;
pub use super::promotions::Entity as Promotions;
pub use super::riot_ids::Entity as RiotIds;
pub use super::summoners::Entity as Summoners;
